# Install and setup the following components for each system in the following order.
---
macosx:
  - dotfiles # Base setup.
  - localrc
  - zsh
  # # - test
  - shell
  - git
  - homebrew
  - vim
  - macosx
  - xcode
  - node
  - ruby

linux:
