# Install and setup the following components for each system in the following order.
---
macosx:
  - homebrew # This need's to run first due to cmd dependency
  - dotfiles
  - localrc
  - zsh
  - shell
  - git
  - vim
  - macosx
  - xcode
  - node
  - ruby

linux:
